### ISSUE TITLE
Easy recipes

### ISSUE THREAD

**Issue by zeromic** [DoughnutTeam/ProjectGreg#6]
Tool forge: There are default recipies for the Tool forge which are easier. itemid: 1104:5

Ender Chest: NEI shows default recipies for Ender Chest and Tanks when you look for blaze rod usage (not tried if they work). itemid: 1268: (wool color difference)

**Comment by DoughnutDev** [comment]
Thanks for the help first off. So I checked the EnderChest issue and this is what I got from testing that http://puu.sh/kZTkC/165ce14a74.png It may just be something in the mods code saying it was that recipe but I override it. So that is fine.

Now the tool forge I found that the slab version is easy I will just be removing that for now.

**Comment by DoughnutDev** [comment]
Both issues are fixed or fixed to the best of my abilities in RC-0.1.2.
